name: Minify CSS and JS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install --global minify

      - name: Minify CSS and JS files
        run: |
          minify -c . --js --css

      - name: Check for changes
        id: changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --global user.name "MinifyBot"
          git config --global user.email "minify@example.com"
          git add -A
          git commit -m "Minify CSS and JS files"
          git push
